jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          repository: marceloNascimentoDev/my-deploy
          path: k8s-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/vitoriadinizdev/my-node-app:${{ github.sha }} .
          docker push ghcr.io/vitoriadinizdev/my-node-app:${{ github.sha }}

      - name: Update deployment.yaml1
        run: |
          sed -i "s|ghcr.io/vitoriadinizdev/my-node-app:.*|ghcr.io/vitoriadinizdev/my-node-app:${{ github.sha }}|g" k8s-repo/k8s/deployment.yaml

      - name: Commit and push
        run: |
          cd k8s-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
